# Travis-CI Build for RfidResearchGroup/Proxmark3
language: c

#default linux build env is: xenial
compiler: gcc

# move some env variables to homebrew env
env:
  global:
    - HOMEBREW_TRAVIS_BRANCH=$TRAVIS_BRANCH
    - HOMEBREW_TRAVIS_COMMIT=$TRAVIS_COMMIT

# Test on Linux and MacOS
matrix:
  include:
    - os: osx
      osx_image: xcode11
      env: MAKE_PARAMS='PLATFORM_EXTRAS='
    - os: osx
      osx_image: xcode11
      env: MAKE_PARAMS='PLATFORM_EXTRAS=BTADDON'
    - os: linux
      dist: xenial
      sudo: required
      env: MAKE_PARAMS='PLATFORM_EXTRAS='
    - os: linux
      dist: xenial
      sudo: required
      env: MAKE_PARAMS='PLATFORM_EXTRAS=BTADDON'

addons:
  apt:
    packages:
      - gcc-arm-none-eabi
      - libnewlib-dev
  homebrew:
    packages:
      - readline
      - p7zip
      - libusb-compat
      - perl
      - qt5
      - wget
      - RfidResearchGroup/proxmark3/arm-none-eabi-gcc
    taps: RfidResearchGroup/proxmark3

install:
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew update;
    brew info proxmark3;
    brew options proxmark3;
    make clean;
    make all V=1 "$MAKE_PARAMS";
  elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    make clean;
    make all V=1 "$MAKE_PARAMS";
  fi

script:
## start and run a test script
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    ./pm3test.sh;  
  elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    ./pm3test.sh;
  fi
