# Travis-CI Build for Iceman Fork / Proxmark3
language: c

#default linux build env is: Ubuntu 14.04 trusty
dist: trusty
sudo: required

#install:
compiler: gcc

# multi platform build test
# build matrix,  
# LINUX : Using trusty beta build environment,  based on Ubuntu 14.04
# MAC OS: 
matrix:
  include:
    - os: osx
      osx_image: xcode7.3
  allow_failures:
    - os: osx

# MAC OS - dependencies?
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi

## Install mainline ARM toolchain.  gcc-arm-none-eabi is available
## in Ubuntu >= 14.04, but this external PPA is needed for 12.04.
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu trusty main universe multiverse restricted'; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo apt-get install -y gcc-arm-none-eabi; fi
  - git fetch --all

#make command
script: "make all"