# Travis-CI Build for IcemanFork/Proxmark3
language: c

#default linux build env is: Ubuntu 14.04 trusty
dist: trusty
sudo: required

#install:
compiler: gcc

# multi platform build test
# build matrix,  
# LINUX : Using trusty beta build environment,  based on Ubuntu 14.04
# MAC OS: 
matrix:
  include:
    - os: osx
      osx_image: xcode7.3
  allow_failures:
    - os: osx

# MAC OS - dependencies?
#before_install:
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap iceman1001/proxmark3; fi

## Install mainline ARM toolchain.  gcc-arm-none-eabi is available
## in Ubuntu >= 14.04, but this external PPA is needed for 12.04.
before_script:
  - if  [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
  - sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu trusty main universe multiverse restricted';
  - sudo apt-get update -qq;
  - sudo apt-get install -y gcc-arm-none-eabi;
  - git fetch --all
  - elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
  - brew update;
  - brew tap iceman1001/proxmark3;
  - brew install proxmark3;
  fi
#make command
script: "make all"