os: Windows Server 2012
platform: mingw
qt: mingw492_32

branches:
  only:
    - master

install:
 - set QTDIR=C:\Qt\5.5\mingw492_32
 - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
  
before_build:
 - make clean
 
build:
  - make all
