name: MacOS Build and Test

on: [push, pull_request]

jobs:
  build-make:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set Git http.postBuffer to something high
        run: git config --global http.postBuffer 524288000
      - name: Update brew repos
        run: brew update
      - name: Tap RfidResearchGroup/proxmark3
        run: brew tap RfidResearchGroup/proxmark3
      - name: Install dependencies
        run: brew install readline qt5 RfidResearchGroup/proxmark3/arm-none-eabi-gcc
      - name: Build
        run: make clean && make V=1
      - name: Test
        run: make check

  build-make-btaddon:
    if: always()
    needs: [build-make]
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set Git http.postBuffer to something high
        run: git config --global http.postBuffer 524288000
      - name: Update brew repos
        run: brew update
      - name: Tap RfidResearchGroup/proxmark3
        run: brew tap RfidResearchGroup/proxmark3
      - name: Install dependencies
        run: brew install readline qt5 RfidResearchGroup/proxmark3/arm-none-eabi-gcc
      - name: Build
        run: make clean && make V=1 PLATFORM_EXTRAS=BTADDON
      - name: Test
        run: make check

  build-cmake:
    if: always()
    needs: [build-make, build-make-btaddon]
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set Git http.postBuffer to something high
        run: git config --global http.postBuffer 524288000
      - name: Update brew repos
        run: brew update
      - name: Tap RfidResearchGroup/proxmark3
        run: brew tap RfidResearchGroup/proxmark3
      - name: Install dependencies
        run: brew install readline qt5 RfidResearchGroup/proxmark3/arm-none-eabi-gcc
      - name: Build
        run: mkdir -p client/build && ( cd client/build && cmake .. && make VERBOSE=1 )
      - name: Test
        run: make client/check CHECKARGS="--clientbin ./client/build/proxmark3"
