name: MacOS Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update brew repos
      run: brew update
    - name: Update packages
      run: brew upgrade
    - name: Tap RfidResearchGroup/proxmark3
      run: brew tap RfidResearchGroup/proxmark3
    - name: Install dependencies
      run: readline qt5 RfidResearchGroup/proxmark3/arm-none-eabi-gcc
    - name: Build
      run: make clean && make V=1
    - name: Test
      run: make check
